### PR TITLE
Non conda

### PR DESCRIPTION
**Pull request by hainm**

### CODE REVIEW

**Comment by hainm** [comment]
merge. Stupid error on macs is due to shell_session_update.

**Comment by swails** [comment]
[Just do what I do](https://github.com/ParmEd/ParmEd/blob/master/devtools/ci/travis/runtest.sh#L44-L46)  :smiley:

**Comment by hainm** [comment]
@swails I[ did steal that from you](https://github.com/Amber-MD/install_ambertools/blob/master/scripts/dummy.sh) but getting weird error if using "source amber.sh"

https://travis-ci.org/Amber-MD/install_ambertools/jobs/224511426#L1353
```bash
$ source $HOME/amber17/amber.sh
AMBERHOME = /Users/travis/amber17
Faking shell_session_update
/Users/travis/amber17 Faking shell_session_update/lib/python2.7/site-packages/
```

I guess using too much `source` is evil.

**Comment by swails** [comment]
> I guess using too much source is evil.

haha -- I can't tell if you're serious or not, but there is nothing wrong with using "source" as many times as you want.  Standard Linux login shells do it behind-the-scenes all the time (it sources every file in /etc/profile.d, for instance).

**Comment by hainm** [comment]
I see. (I am serious about that saying).

I guess travis is evil. ha ha.

**Pull request merged**
